//
//  LogoutPresenter.swift
//  Kiwari-ios-test
//
//  Created by daniel on 10/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogoutPresentationLogic
{
  func presentSomething(response: Logout.Something.Response)
}

class LogoutPresenter: LogoutPresentationLogic
{
  weak var viewController: LogoutDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Logout.Something.Response)
  {
    let viewModel = Logout.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
