//
//  LogoutInteractor.swift
//  Kiwari-ios-test
//
//  Created by daniel on 10/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogoutBusinessLogic
{
    func doSomething(request: Logout.Something.Request)
}

protocol LogoutDataStore
{
    //var name: String { get set }
}

class LogoutInteractor: LogoutBusinessLogic, LogoutDataStore
{
    var presenter: LogoutPresentationLogic?
    var worker: LogoutWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Logout.Something.Request)
    {
        worker = LogoutWorker()
        worker?.doSomeWork()
        
        let response = Logout.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
