//
//  LoginModels.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum LoginUser
  {
    struct Request
    {
       var email: String?
       var password: String?
    }
    struct Response
    {
        var data: Result<Bool, Error>
    }
    struct ViewModel
    {
        var data: Result<Bool, Error>
    }
  }
}
