//
//  LoginWorker.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    
    func checkUser(request:Login.LoginUser.Request, completion: @escaping (_ valid: Bool)->()) {
        DispatchQueue.global(qos: .background).async {
            let userItem = Hardcodeduser.setHardcodedUser()
            
            if userItem[0].email == request.email && userItem[0].password == request.password {
                AppState.sharedInstance.setupAuthorizedState(user: userItem[0])
                DispatchQueue.main.async {
                    completion(true)
                }
            } else if userItem[1].email == request.email && userItem[1].password == request.password {
                AppState.sharedInstance.setupAuthorizedState(user: userItem[1])
               DispatchQueue.main.async {
                    completion(true)
                }
            } else {
              DispatchQueue.main.async {
                    completion(false)
                }
            }
            
        }
    }
    
}
