//
//  LoginPresenter.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentLoginUser(res: Login.LoginUser.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: present Login Response
  
    func presentLoginUser(res: Login.LoginUser.Response) {
        viewController?.displayLoginUser(vm: Login.LoginUser.ViewModel(data: res.data))
    }
}
