//
//  LoginRouter.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToChats(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToChats(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ChatsViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToChats(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "Chats") as! ChatsViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToChats(source: dataStore!, destination: &destinationDS)
      navigateToChats(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToChats(source: LoginViewController, destination: ChatsViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToChats(source: LoginDataStore, destination: inout ChatsDataStore)
  {
    //destination.name = source.name
  }
}
