//
//  LoginInteractor.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func isUserValid(email: String?, password: String?)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker = LoginWorker()
    //var name: String = ""
    
    func isUserValid(email: String?, password: String?) {
        worker.checkUser(request: Login.LoginUser.Request(email: email, password: password)) { (isValid) in
            self.presenter?.presentLoginUser(res: Login.LoginUser.Response(isValid: isValid, error: nil))
        }
    }
    
}
