//
//  ChatsViewController.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsDisplayLogic: class
{
  func displaySomething(viewModel: Chats.Something.ViewModel)
}

class ChatsViewController: UIViewController, ChatsDisplayLogic
{
  var interactor: ChatsBusinessLogic?
  var router: (NSObjectProtocol & ChatsRoutingLogic & ChatsDataPassing)?
    
    
    @IBOutlet weak var navBar: NavigationBarChatView!
    @IBOutlet weak var chatTable: UITableView!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ChatsInteractor()
    let presenter = ChatsPresenter()
    let router = ChatsRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    setupView()
    doSomething()
    
    chatTable.register(UINib(nibName: "ChatTableViewCell", bundle: nil), forCellReuseIdentifier: "ChatTableViewCell")
    chatTable.rowHeight = UITableView.automaticDimension
     chatTable.estimatedRowHeight = 10.0
    
    navBar.setupView(user: User2())
  }
    
    func setupView() {
     
      
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Chats.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Chats.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension ChatsViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        2
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
         let cell = self.chatTable.dequeueReusableCell(withIdentifier: "ChatTableViewCell") as! ChatTableViewCell
        
        return cell

    }
    

    
    
}
