//
//  ChatsInteractor.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsBusinessLogic
{
    func fetchChat(request :Chats.ChatModel.Request)
    func listenChat(request: Chats.ListenChat.Request)
    func addChat(request: Chats.AddChat.Request)
}

protocol ChatsDataStore
{
    var chat: [Chat]? {get set}
}

class ChatsInteractor: ChatsBusinessLogic, ChatsDataStore
{
  
    var presenter: ChatsPresentationLogic?
    var chat: [Chat]?
    var worker: ChatsWorker = ChatsWorker()
    
    func fetchChat(request: Chats.ChatModel.Request) {
        worker.getCollection { data in
            self.chat = data
            self.presenter?.presentChat(response: Chats.ChatModel.Response(chat: data))
        }
      }
    
    func listenChat(request: Chats.ListenChat.Request) {
        worker.changeListener { data in
            guard let chat = data else {return}
            self.chat?.append(chat)
            self.presenter?.presentListenerChat(response: Chats.ListenChat.Response(chat: chat))
        }
    }
    
    func addChat(request: Chats.AddChat.Request) {
        worker.addChat(req: request) { err in
            print(err)
        }
    }
}
