//
//  ChatsInteractor.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsBusinessLogic
{
    func fetchChat(request :Chats.ChatModel.Request)
}

protocol ChatsDataStore
{
    
}

class ChatsInteractor: ChatsBusinessLogic, ChatsDataStore
{
  
    
    var presenter: ChatsPresentationLogic?
    var worker: ChatsWorker = ChatsWorker()
    
    func fetchChat(request: Chats.ChatModel.Request) {
        worker.getCollection { data in
            self.presenter?.presentChat(response: Chats.ChatModel.Response(chat: data))
        }
      }
}
