//
//  ChatsPresenter.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsPresentationLogic
{
  func presentSomething(response: Chats.Something.Response)
}

class ChatsPresenter: ChatsPresentationLogic
{
  weak var viewController: ChatsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Chats.Something.Response)
  {
    let viewModel = Chats.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
