//
//  ChatsInteractor.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsBusinessLogic
{
    func fetchChat(request :Chats.ChatModel.Request)
    func listenChat(request: Chats.ListenChat.Request)
    func addChat(request: Chats.AddChat.Request)
}

protocol ChatsDataStore
{
    var chat: [Chat]? {get set}
}

class ChatsInteractor: ChatsBusinessLogic, ChatsDataStore
{
    
    var presenter: ChatsPresentationLogic?
    var chat: [Chat]?
    var worker: ChatsWorker = ChatsWorker()
    
    func fetchChat(request: Chats.ChatModel.Request) {
        worker.getCollection { data in
            switch data {
            case .success(let chats) : self.chat = chats
            case .failure(_):
                print("error")
            }
            
            self.presenter?.presentChat(response: Chats.ChatModel.Response(data: data))
        }
    }
    
    func listenChat(request: Chats.ListenChat.Request) {
        worker.changeListener { data in
            switch data {
            case .success(let chat) : self.chat?.append(chat)
            case.failure(_) : print("error getting single data")
            }
            self.presenter?.presentListenerChat(response: Chats.ListenChat.Response(data: data))
        }
    }
    
    func addChat(request: Chats.AddChat.Request) {
        worker.addChat(req: request) { err in
            print(err)
        }
    }
}
