//
//  ChatsRouter.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatsRoutingLogic
{
}

protocol ChatsDataPassing
{
    var dataStore: ChatsDataStore? { get }
}

class ChatsRouter: NSObject, ChatsRoutingLogic, ChatsDataPassing
{
    weak var viewController: ChatsViewController?
    var dataStore: ChatsDataStore?
    
}
