//
//  ChatsModels.swift
//  Kiwari-ios-test
//
//  Created by daniel on 08/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chats
{
    // MARK: Use cases
    
    
    enum ChatModel {
        struct Request {
            
        }
        
        struct Response {
            var chat: [Chat]
        }
        
        struct ViewModel {
            var chat: [Chat] 
        }
    }
    
    enum ListenChat {
        struct Request {
            
        }
        
        struct Response {
            var chat: Chat
        }
        
        struct ViewModel {
            var chat: Chat
        }
    }
}
